# Generated by Django 5.1.1 on 2024-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_caragory_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
