# Generated by Django 5.1.1 on 2024-09-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caragory',
            new_name='Catagory',
        ),
    ]
