# Generated by Django 5.1.1 on 2024-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='telegram',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
