# Generated by Django 5.1.1 on 2024-09-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_item_telegram_item_color_item_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
