# Generated by Django 5.1.1 on 2024-09-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
    ]
