# Generated by Django 5.1.1 on 2024-09-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_remove_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='caragory',
            new_name='Catagory',
        ),
    ]
