# Generated by Django 5.1.1 on 2024-09-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_rename_caragory_item_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Catagory',
            new_name='catagory',
        ),
    ]
