# Generated by Django 5.1.1 on 2024-09-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_rename_catagory_item_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
    ]
