# Generated by Django 5.1.1 on 2024-10-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=' 1', on_delete=django.db.models.deletion.CASCADE, to='item.category'),
        ),
    ]
