# Generated by Django 5.1.1 on 2024-10-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=' 1', null=True, on_delete=django.db.models.deletion.CASCADE, to='item.category'),
        ),
    ]
